services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 2060
      MYSQL_DATABASE: ekramnew
      TZ: Asia/Tehran
    volumes:
      - ./db_data:/var/lib/mysql
      - ./:/var/www
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 4000:80